---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kustomize-apps
  namespace: mroosing
spec:
  interval: 10m0s
  path: ./exercises/kustomize-controller/staging
  prune: true
  serviceAccountName: flux-reconciler
  sourceRef:
    kind: GitRepository
    name: flux-fundamentals

