---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster
  namespace: mroosing
spec:
  interval: 10m0s
  path: ./cluster/staging
  prune: false
  serviceAccountName: flux-reconciler
  sourceRef:
    kind: GitRepository
    name: flux-fundamentals

